const sanitizer = require('sanitize-html');

const dirty = `
<!DOCTYPE html>
        <html>
            <head>
                <meta name = "viewport" content="width=device-width, initial-scale=1">
                <style type="text/css">
                    body{
                        font-family: Verdana, sans-serif;
                    }
                </style>
            </head>
            <body>
<div class="quads-location quads-ad3" id="quads-ad3" style="float:none;margin:0px 0 0px 0;text-align:center;">
<script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: block; text-align: center; height: 117px;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-9638064869561472" data-ad-slot="6075996024" data-adsbygoogle-status="done"><ins id="aswift_1_expand" style="display:inline-table;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_1_anchor" style="display:block;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="117" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_1" name="aswift_1" style="left:0;position:absolute;top:0;border:0px;width:467px;height:117px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div><p><img class="size-medium wp-image-33573 aligncenter" src="https://i0.wp.com/warstek.com/wp-content/uploads/2019/10/Ikan-Lele1-e1495627794210-300x233.jpg?resize=300%2C233&amp;ssl=1" alt="" width="300" height="233" srcset="https://i1.wp.com/warstek.com/wp-content/uploads/2019/10/Ikan-Lele1-e1495627794210.jpg?resize=300%2C233&amp;ssl=1 300w, https://i1.wp.com/warstek.com/wp-content/uploads/2019/10/Ikan-Lele1-e1495627794210.jpg?w=400&amp;ssl=1 400w" sizes="(max-width: 300px) 100vw, 300px"></p>
<p style="text-align: justify;">Lele (<em>Clarias batracus</em>) merupakan&nbsp; salah satu komoditas perikanan yang banyak dibudidayakan oleh masyarakat. Ikan lele merupakan jenis ikan air tawar yang memiliki tubuh memanjang, pipih serta tubuh yang licin berlendir. Ikan lele diminati masyarakat karena memiliki berbagai kelebihan, seperti mampu beradaptasi pada segala kondisi, dagingnya gurih dan enak bila dikonsumsi, pertumbuhan cepat, dan memiliki kandungan gizi yang tinggi bagi kesehatan. Menurut buku pedoman analisis zat gizi yang diterbitkan oleh Direktorat Bina Gizi Masyarakat dan Puslitbang Depkes RI tahun 1991, ikan lele memiliki kandungan kadar air 76 gr, protein 17 gr, lemak 4,5 gr, fosfor 200 mg, kalsium 20 mg, zat besi 1 gr, vitamin A 150 IU (International Unit) dan vitamin B1 0,05 gr.</p>
<p style="text-align: justify;">Selan itu, ikan lele juga mengandung asam lemak omega-3 13,6 gr/100 gr, asam lemak omega-6 22,2 gr/100 gr dan asam lemak omega-9 19,5 gr/100gr [1]. Tingginya kandungan omega-6 pada ikan lele dapat digunakan untuk perkembangan gizi pada anak-anak , khususnya balita. Omega-6 dikenal dapat membantu perkembangan otak yang berperan dalam peningkatan prestasi akademik anak. Kandungan gizi inilah yang dinilai lebih tinggi dibandingkan dengan jenis ikan lainnya seperti ikan salmon dan tuna yang harganya lebih mahal daripada ikan lele.</p>
<div class="quads-location quads-ad5" id="quads-ad5" style="float:none;margin:0px 0 0px 0;text-align:center;">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: block; text-align: center; height: 117px;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-9638064869561472" data-ad-slot="2754939514" data-adsbygoogle-status="done"><ins id="aswift_2_expand" style="display:inline-table;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_2_anchor" style="display:block;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="117" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_2" name="aswift_2" style="left:0;position:absolute;top:0;border:0px;width:467px;height:117px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div><p style="text-align: justify;">Tetapi pernahkah kita berpikir bahwa lendir pada tubuh lele juga bermanfaat untuk dunia medis?</p>
<p style="text-align: justify;">Sebelum kita bicara mengenai manfaat lendir ikan lele untuk dunia medis, kita kenali dulu fungsi lendir yang ada pada tubuhnya untuk ikan lele itu sendiri. Lendir ikan lele berfungsi sebagai pelindung diri karena lele tidak memiliki sisik. Selain itu lendirnya juga berfungsi sebagai media bergerak lele, baik di dalam lumpur ataupun di dalam air [2]. Lalu apa saja manfaat lele untuk dunia medis?</p>
<p style="text-align: justify;"><strong>Sebagai Obat Penyembuh Luka pada Penderita Diabetes </strong></p>
<p style="text-align: justify;">Lendir pada tubuh lele juga dapat digunakan sebagai obat luka pada penderita diabetes kronis. Khususnya penderita diabetes yang telah terinfeksi oleh bakteri Methicillin Resistant <em>Staphylococcus aureus</em> (MRSA). Kandungan <em>Antimicrobial peptides</em> dalam lendir lele inilah yang dapat melawan bakteri patogen penyebab luka pada penderita diabetes kronis [3].</p>
<p style="text-align: justify;"><strong>&nbsp;</strong><strong>Lalu apa itu bakteri MRSA?</strong></p>
<p style="text-align: justify;">Bakteri Methicillin Resistant Staphylococcus aureus (MRSA) merupakan bakteri <em>Staphylococcus aureus</em> yang telah kebal terhadap antibiotik. Pemicu bakteri ini mengalami resistensi adalah terapi antibiotik yang tidak rasional. Bakteri ini berpindah dari satu pasien ke pasien lainnya, baik melalui alat medis yang kurang steril, maupun melalui udara. Banyak sekali faktor yang dapat memicu terjadinya MRSA ini, yaitu lingkungan, kebersihan individu, riwayat infeksi, riwayat operasi dan penyakit, serta riwayat pengobatan [4].</p>
<p style="text-align: justify;"><strong>Sebagai Formulasi Saliva Buatan dalam Mengatasi Mulut Kering Pasca terapi kanker Nasofaring.</strong></p>
<div class="quads-location quads-ad3" id="quads-ad3" style="float:none;margin:0px 0 0px 0;text-align:center;">
<script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: block; text-align: center; height: 117px;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-9638064869561472" data-ad-slot="6075996024" data-adsbygoogle-status="done"><ins id="aswift_3_expand" style="display:inline-table;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_3_anchor" style="display:block;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="117" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_3" name="aswift_3" style="left:0;position:absolute;top:0;border:0px;width:467px;height:117px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div><p style="text-align: justify;">Salah satu efek yang dihasilkan pasca kemoterapi pasien penderita kanker nasofaring adalah kondisi mulut kering bahkan susah dalam proses menelan. Karena itu, dapat diatasi dengan perawatan menggunakan saliva buatan. Namun, produk saliva buatan yang beredar di pasaran Indonesia belum menggunakan bahan-bahan organik. Alternatif yang bisa dipakai ialah menggunakan formulasi lendir lele sebagai saliva buatan. Di dalam lendir lele, mengandung senyawa-senyawa antimikroba seperti claricin, hepcidin, dan protease. Dimana senyawa-senyawa ini dapat melawan bakteri dan jamur penyebab mulut kering pada pasien pasca kemoterapi kanker nasofaring [5]. Wow, meskipun lele hidup di lingkungan kompleks dan lingkungan tercemar sekalipun, tetapi lele punya manfaat luar biasa.</p>
<div class="quads-location quads-ad4" id="quads-ad4" style="float:none;margin:0px;">
Baca juga:
<br>
<script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: inline-block; width: 467.281px; height: 150px;" data-ad-client="ca-pub-9638064869561472" data-ad-slot="5198682179" data-adsbygoogle-status="done"><ins id="aswift_4_expand" style="display:inline-table;border:none;height:150px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_4_anchor" style="display:block;border:none;height:150px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="150" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_4" name="aswift_4" style="left:0;position:absolute;top:0;border:0px;width:467px;height:150px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div><p>&nbsp;</p>
<p>&nbsp;</p>
<p style="text-align: justify;">Referensi :</p>
<p style="text-align: justify;">[4] Mahmudah, R., T. U. Sholeha, dan CN. Ekowati. 2013. Identifikasi Methicillin-Resistant <em>Staphylococcus aureus</em> (MRSA) pada Tenaga Medis dan Paramedis di Ruang Intensivecare Unit (ICU) dan Ruang Perawatan Bedah Rumah Sakit Umum Daerah Abdul Moeloek. Medical Journal of Lampung University Vol 2(4). Halaman 70-78.</p>
<p style="text-align: justify;">[1] Nurasmi., &nbsp;A. P. Sari dan Rusmiati. 2018. Analisis Kandungan Asam Lemak Omega 3, Omega 6 dan Omega 9 dari Ikan Lele (<em>Clarisas sp</em>) pada Peningkatan Nutrisi Balita. Journal of Borneo Holistic Health. Vol 1(1). Halaman 99-100.</p>
<p style="text-align: justify;">[2] Remi. (2015, 10 Oktober). Karakteristik Tubuh Ikan Lele. Dikutip 18 Oktober 2019 dari https//ternakpedia.com/10/karakterist-lele/.</p>
<p style="text-align: justify;">[3] Kurniawan, B. (2016, 5 Agustus). Lendir lele Berkhasiat Obati Luka Diabetes. Dikutip18 Oktober 2019 dari <a href="https://m.detik.com/health/berita-detikhealth/lendir-lele-berkhasiat-obati-luka-diabetes">https://m.detik.com/health/berita-detikhealth/lendir-lele-berkhasiat-obati-luka-diabetes</a>.</p>
<p style="text-align: justify;">[4] Mahmudah, R., T. U. Sholeha, dan CN. Ekowati. 2013. Identifikasi Methicillin-Resistant <em>Staphylococcus aureus</em> (MRSA) pada Tenaga Medis dan Paramedis di Ruang Intensivecare Unit (ICU) dan Ruang Perawatan Bedah Rumah Sakit Umum Daerah Abdul Moeloek. Medical Journal of Lampung University Vol 2(4). Halaman 70-78.</p>
<p style="text-align: justify;">[5] Sabandar, S. (2018, 21 Juli). Mahasiswa UGM Temukan Khasiat lendir Lele untuk Pasien Kanker. Dikutip 18 Oktober 2019 dari&nbsp; https://m.liputan6.com/mahasiswa-ugm-temukan-khasiat-lendir-lele-untuk-pasien-kanker.
</p><div class="quads-location quads-ad9" id="quads-ad9" style="float:none;margin:0px;">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: block; height: 280px;" data-ad-client="ca-pub-9638064869561472" data-ad-slot="6610424045" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done"><ins id="aswift_5_expand" style="display:inline-table;border:none;height:280px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_5_anchor" style="display:block;border:none;height:280px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="280" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_5" name="aswift_5" style="left:0;position:absolute;top:0;border:0px;width:467px;height:280px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div><p></p>
<div class="abh_box abh_box_down abh_box_"><ul class="abh_tabs"> <li class="abh_about abh_active"><a href="#abh_about">About</a></li> <li class="abh_posts"><a href="#abh_posts">Latest Posts</a></li></ul><div class="abh_tab_content"><section class="vcard abh_about_tab abh_tab" style="display:block"><div class="abh_image"><a href="https://warstek.com/author/annisach/" class="url" title=""> <img src="https://i0.wp.com/warstek.com/wp-content/uploads/2017/12/logo-warstek-bulat.png?resize=250%2C250&amp;ssl=1" class="gravatar avatar avatar-250 um-avatar um-avatar-default" width="80" height="80" alt="Annisach" data-default="https://i0.wp.com/warstek.com/wp-content/uploads/2017/12/logo-warstek-bulat.png?resize=250%2C250&amp;ssl=1" onerror="if ( ! this.getAttribute('data-load-error') ){ this.setAttribute('data-load-error','1');this.setAttribute('src', this.getAttribute('data-default'));}"></a></div><div class="abh_social"></div><div class="abh_text"><h3 class="fn name"><a href="https://warstek.com/author/annisach/" class="url"></a></h3><div class="abh_job"></div><div class="description note abh_description"></div></div></section><section class="abh_posts_tab abh_tab"><div class="abh_image"><a href="https://warstek.com/author/annisach/" class="url" title=""><img src="https://i0.wp.com/warstek.com/wp-content/uploads/2017/12/logo-warstek-bulat.png?resize=250%2C250&amp;ssl=1" class="gravatar avatar avatar-250 um-avatar um-avatar-default" width="250" height="250" alt="Annisach" data-default="https://i0.wp.com/warstek.com/wp-content/uploads/2017/12/logo-warstek-bulat.png?resize=250%2C250&amp;ssl=1" onerror="if ( ! this.getAttribute('data-load-error') ){ this.setAttribute('data-load-error','1');this.setAttribute('src', this.getAttribute('data-default'));}"></a></div><div class="abh_social"></div><div class="abh_text"><h4>Latest posts by<span class="abh_allposts">(<a href="https://warstek.com/author/annisach/">see all</a>)</span></h4><div class="abh_description note"><ul> <li> <a href="https://warstek.com/2019/10/27/lendir-lele/">Mengenal Lebih Dekat Manfaat Lendir Lele Bagi Kesehatan</a><span> - 27 Oktober 2019</span> </li></ul></div></div></section></div></div><div class="quads-location quads-ad2" id="quads-ad2" style="float:none;margin:0px 0 0px 0;text-align:center;">
Artikel Berhubungan:
<br>
<script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: block; height: 1606px;" data-ad-format="autorelaxed" data-ad-client="ca-pub-9638064869561472" data-ad-slot="4368873124" data-adsbygoogle-status="done"><ins id="aswift_6_expand" style="display:inline-table;border:none;height:1606px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_6_anchor" style="display:block;border:none;height:1606px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="1606" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_6" name="aswift_6" style="left:0;position:absolute;top:0;border:0px;width:467px;height:1606px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script>
<br>
Sponsor Warstek.com:
<script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display: block; text-align: center; height: 117px;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-9638064869561472" data-ad-slot="2972030973" data-adsbygoogle-status="done"><ins id="aswift_7_expand" style="display:inline-table;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><ins id="aswift_7_anchor" style="display:block;border:none;height:117px;margin:0;padding:0;position:relative;visibility:visible;width:467px;background-color:transparent;"><iframe width="467" height="117" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_7" name="aswift_7" style="left:0;position:absolute;top:0;border:0px;width:467px;height:117px;"></iframe></ins></ins></ins>
<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div></body>
        </html>
`


exports.sanitize = () =>{
    return sanitizer(dirty, 
    {
        allowedTags: ['img','h1','h2','p', 'a'],
    });
}
